baseURL = 'https://robins-parties.com/'
locale = 'en-us'
title = "Robin's Parties!"

[[module.mounts]]
source = 'static'
target = 'static'

[[module.mounts]]
source = 'images'
target = 'static/images'

[permalinks]
  "/" = "/:filename"

[markup.goldmark.renderer]
unsafe = true  # allow raw HTML in markdown files
